<?php
$errors=array();
$errors[0]['resultcode']=0;$errors[0]['resultmessage']='Ошибок нет!';
$errors[1]['resultcode']=1;$errors[1]['resultmessage']='Нет такой команды!';
$errors[2]['resultcode']=2;$errors[2]['resultmessage']='Параметр orderid не получен!';
$errors[3]['resultcode']=3;$errors[3]['resultmessage']='Параметр action не получен!';
$errors[4]['resultcode']=4;$errors[4]['resultmessage']='Параметр orderRefuse не получен!';
$errors[5]['resultcode']=5;$errors[5]['resultmessage']='Параметр pwdRefuse не получен!';
$errors[6]['resultcode']=6;$errors[6]['resultmessage']='Параметр count не получен!';
$errors[7]['resultcode']=7;$errors[7]['resultmessage']='Пароль на отказ не верный!';
$errors[8]['resultcode']=8;$errors[8]['resultmessage']='Параметр orderRefuse.id не получен!';
$errors[9]['resultcode']=9;$errors[9]['resultmessage']='Параметр orderRefuse.printer не получен!';
$errors[10]['resultcode']=10;$errors[10]['resultmessage']='Параметр orderRefuse.price не получен!';
$errors[11]['resultcode']=11;$errors[11]['resultmessage']='Ошибка выполнения запроса при отказе!';
$errors[12]['resultcode']=12;$errors[12]['resultmessage']='Пароль при отказе не верный!';
$errors[13]['resultcode']=13;$errors[13]['resultmessage']='Смена не открыта!';
$errors[14]['resultcode']=14;$errors[14]['resultmessage']='Ошибка выполнения запроса при проверке смены!';
$errors[15]['resultcode']=15;$errors[15]['resultmessage']='Ошибка выполнения запроса при загрузке меню!';
$errors[16]['resultcode']=16;$errors[16]['resultmessage']='Ошибка выполнения запроса при загрузке типов оплат!';
$errors[17]['resultcode']=17;$errors[17]['resultmessage']='Ошибка выполнения запроса при выборе сотрудника!';
$errors[18]['resultcode']=18;$errors[18]['resultmessage']='Параметр userpwd не получен!';
$errors[19]['resultcode']=19;$errors[19]['resultmessage']='Параметр employeeid не получен!';
$errors[20]['resultcode']=20;$errors[20]['resultmessage']='Ошибка выполнения запроса при загрузке счетов в интерфейсе кассира!';
$errors[21]['resultcode']=21;$errors[21]['resultmessage']='Смена уже открыта!';
$errors[22]['resultcode']=22;$errors[22]['resultmessage']='Смена уже закрыта!';
$errors[23]['resultcode']=23;$errors[23]['resultmessage']='Ошибка выполнения запроса при открытии смены!';
$errors[24]['resultcode']=24;$errors[24]['resultmessage']='Нельзя закрыть смену, если есть не оплаченные счета. Пожалуйста, оплатите не закрытые счета!';
$errors[25]['resultcode']=25;$errors[25]['resultmessage']='Ошибка выполнения запроса при проверке сотрудника!';
$errors[26]['resultcode']=26;$errors[26]['resultmessage']='Сотрудника с таким id не существует!';
$errors[27]['resultcode']=27;$errors[27]['resultmessage']='Параметр chooseTable не получен!';
$errors[28]['resultcode']=28;$errors[28]['resultmessage']='Ошибка выполнения запроса при выборе клиентов!';
$errors[29]['resultcode']=29;$errors[29]['resultmessage']='Ошибка выполнения запроса при выборе столов!';
$errors[30]['resultcode']=30;$errors[30]['resultmessage']='Ошибка выполнения запроса при выборе скидок!';
$errors[31]['resultcode']=31;$errors[31]['resultmessage']='Ошибка выполнения запроса при выборе примечаний!';
$errors[32]['resultcode']=32;$errors[32]['resultmessage']='Параметр itemid не получен!';
$errors[33]['resultcode']=33;$errors[33]['resultmessage']='Параметр chooseTable имеет не корректное значение!';
$errors[34]['resultcode']=34;$errors[34]['resultmessage']='Ошибка выполнения запроса при загрузке счетов в интерфейсе оффицианта!';
$errors[35]['resultcode']=35;$errors[35]['resultmessage']='Параметр order не получен!';
$errors[36]['resultcode']=36;$errors[36]['resultmessage']='Параметр ordertable не получен!';
$errors[37]['resultcode']=37;$errors[37]['resultmessage']='Параметр printed не получен!';
$errors[38]['resultcode']=38;$errors[38]['resultmessage']='Параметр closed не получен!';
$errors[39]['resultcode']=39;$errors[39]['resultmessage']='Параметр typePrint не получен!';
$errors[40]['resultcode']=40;$errors[40]['resultmessage']='Параметр sumfromclient не получен!';
$errors[41]['resultcode']=41;$errors[41]['resultmessage']='Параметр order.orderid не получен!';
$errors[42]['resultcode']=42;$errors[42]['resultmessage']='Ошибка при загрузке табличной части заказа!';
$errors[43]['resultcode']=43;$errors[43]['resultmessage']='Параметр order.paymentid не получен!';
$errors[44]['resultcode']=44;$errors[44]['resultmessage']='Параметр order.printed не получен!';
$errors[45]['resultcode']=45;$errors[45]['resultmessage']='Параметр order.closed не получен!';
$errors[46]['resultcode']=46;$errors[46]['resultmessage']='Параметр order.clientid не получен!';
$errors[47]['resultcode']=47;$errors[47]['resultmessage']='Параметр order.totalsum не получен!';
$errors[48]['resultcode']=48;$errors[48]['resultmessage']='Параметр order.employeeid не получен!';
$errors[49]['resultcode']=49;$errors[49]['resultmessage']='Параметр order.discountpercent не получен!';
$errors[50]['resultcode']=50;$errors[50]['resultmessage']='Параметр order.discountsum не получен!';
$errors[51]['resultcode']=51;$errors[51]['resultmessage']='Параметр order.servicepercent не получен!';
$errors[52]['resultcode']=52;$errors[52]['resultmessage']='Параметр order.servicesum не получен!';
$errors[53]['resultcode']=53;$errors[53]['resultmessage']='Параметр ordertable.id не получен!';
$errors[54]['resultcode']=54;$errors[54]['resultmessage']='Параметр ordertable.name не получен!';
$errors[55]['resultcode']=55;$errors[55]['resultmessage']='Параметр ordertable.price не получен!';
$errors[56]['resultcode']=56;$errors[56]['resultmessage']='Параметр ordertable.count не получен!';
$errors[57]['resultcode']=57;$errors[57]['resultmessage']='Параметр ordertable.printer не получен!';
$errors[58]['resultcode']=58;$errors[58]['resultmessage']='Параметр ordertable.summa не получен!';
$errors[59]['resultcode']=59;$errors[59]['resultmessage']='Сумма строки в ordertable не совпадает с количество*цену!';
$errors[60]['resultcode']=60;$errors[60]['resultmessage']='Неправильно рассчитана сумма скидки!';
$errors[61]['resultcode']=61;$errors[61]['resultmessage']='Неправильно рассчитана сумма облуживания!';
$errors[62]['resultcode']=62;$errors[62]['resultmessage']='Итоговая сумма расчитана неверно!';
$errors[63]['resultcode']=63;$errors[63]['resultmessage']='Ошибка запроса при сохранении шапки счета!';
$errors[64]['resultcode']=64;$errors[64]['resultmessage']='Ошибка запроса при сохранении табличной части счета!';
$errors[65]['resultcode']=65;$errors[65]['resultmessage']='Ошибка запроса при создании idout!';
$errors[66]['resultcode']=66;$errors[66]['resultmessage']='Ошибка запроса при загрузке счета!';
$errors[67]['resultcode']=67;$errors[67]['resultmessage']='Ошибка выполнения запроса при проверке счета!';
$errors[68]['resultcode']=68;$errors[68]['resultmessage']='Счет с таким id не существует!';
$errors[69]['resultcode']=69;$errors[69]['resultmessage']='Счет уже был распечатан! ';
$errors[70]['resultcode']=70;$errors[70]['resultmessage']='Счет уже был закрыт!';
$errors[71]['resultcode']=71;$errors[71]['resultmessage']='Ошибка запроса при обновлении табличной части счета!';
$errors[72]['resultcode']=72;$errors[72]['resultmessage']='Ошибка выполнения запроса при проверке типа оплаты!';
$errors[73]['resultcode']=73;$errors[73]['resultmessage']='Типа оплаты с таким id не существует!';
$errors[74]['resultcode']=74;$errors[74]['resultmessage']='Ошибка выполнения запроса при проверке клиента!';
$errors[75]['resultcode']=75;$errors[75]['resultmessage']='Клиента с таким id не существует!';
$errors[76]['resultcode']=76;$errors[76]['resultmessage']='Ошибка выполнения запроса при проверке товара!';
$errors[77]['resultcode']=77;$errors[77]['resultmessage']='Товара с таким id не существует!';
$errors[78]['resultcode']=78;$errors[78]['resultmessage']='Ошибка выполнения запроса при печати счета!';
$errors[79]['resultcode']=79;$errors[79]['resultmessage']='Сумма от клиента меньше суммы счета!';
$errors[80]['resultcode']=80;$errors[80]['resultmessage']='Параметр interface не получен!';
$errors[81]['resultcode']=81;$errors[81]['resultmessage']='Ошибка выполнения запроса при получении параметров интерфейса!';
$errors[82]['resultcode']=82;$errors[82]['resultmessage']='Такого интерфейса не сущетвует!';
$errors[83]['resultcode']=83;$errors[83]['resultmessage']='Ошибка запроса при изменении printed!';
$errors[84]['resultcode']=84;$errors[84]['resultmessage']='Ошибка запроса при оплате!';
$errors[85]['resultcode']=85;$errors[85]['resultmessage']='Параметр unlock pwd не получен!';
$errors[86]['resultcode']=86;$errors[86]['resultmessage']='Ошибка выполнения запроса при проверке пароля на разблокировку счета!';
$errors[87]['resultcode']=87;$errors[87]['resultmessage']='Ошибка выполнения запроса на разблокировку счета!';
$errors[88]['resultcode']=88;$errors[88]['resultmessage']='Неверный пароль на разблокировку счета!';
$errors[89]['resultcode']=89;$errors[89]['resultmessage']='Ошибка выполнения запроса на проверку товара в  счете!';
$errors[90]['resultcode']=90;$errors[90]['resultmessage']='Количество введенное с клавиатуры больше чем количество выбранного товара!';
$errors[91]['resultcode']=91;$errors[91]['resultmessage']='Данный код авторизации отсутствует!';
$errors[92]['resultcode']=92;$errors[92]['resultmessage']='Ошибка выполнения запроса при проверке пароля на выход!';
$errors[93]['resultcode']=93;$errors[93]['resultmessage']='Неверный пароль на выход!';
$errors[94]['resultcode']=94;$errors[94]['resultmessage']='Параметр shtrih не получен!';
$errors[95]['resultcode']=95;$errors[95]['resultmessage']='Ошибка выполнения запроса при выборе товара по штрих-коду!';
$errors[96]['resultcode']=96;$errors[96]['resultmessage']='Товар по введенному штрих-коду не найден!';
$errors[97]['resultcode']=97;$errors[97]['resultmessage']='Ошибка выполнения запроса при выборе информации о смене!';
$errors[98]['resultcode']=98;$errors[98]['resultmessage']='Ошибка выполнения запроса при выборе информации из заказа при расчете подарков!';
$errors[99]['resultcode']=99;$errors[99]['resultmessage']='Ошибка выполнения запроса при выборе информации из автоматизируемой точки!';
$errors[100]['resultcode']=100;$errors[100]['resultmessage']='Ошибка выполнения запроса при вставке баланса!';
$errors[101]['resultcode']=101;$errors[101]['resultmessage']='Ошибка выполнения запроса при выборе баланса у клиента!';
$errors[102]['resultcode']=102;$errors[102]['resultmessage']='Ошибка выполнения запроса при выборе мнимального порога!';
$errors[103]['resultcode']=103;$errors[103]['resultmessage']='Ошибка выполнения запроса при выборе шапки из заказа при сохранении подарков!';
$errors[104]['resultcode']=104;$errors[104]['resultmessage']='Параметр balans не получен!';
$errors[105]['resultcode']=105;$errors[105]['resultmessage']='Разное количество баллов при добавлении подарка!';
$errors[106]['resultcode']=106;$errors[106]['resultmessage']='Ошибка выполнения запроса при определении уровня подарков!';
$errors[107]['resultcode']=107;$errors[107]['resultmessage']='Параметр discountid не получен!';
$errors[108]['resultcode']=108;$errors[108]['resultmessage']='Параметр interfaceid не получен!';
$errors[109]['resultcode']=109;$errors[109]['resultmessage']='Ошибка выполнения запроса при выборе скидки и интерфейса из заказа!';
$errors[110]['resultcode']=110;$errors[110]['resultmessage']='Ошибка выполнения запроса при выборе клиентов по штрихкоду!';
$errors[111]['resultcode']=111;$errors[111]['resultmessage']='Параметр shtrih не получен!';
$errors[112]['resultcode']=112;$errors[112]['resultmessage']='Ошибка выполнения запроса при проверке сессии у сотрудника!';
$errors[113]['resultcode']=113;$errors[113]['resultmessage']='Ошибка выполнения запроса при создании сессии у сотрудника!';
$errors[114]['resultcode']=114;$errors[114]['resultmessage']='Данный сотрудник уже работает под своим интерфейсом!';
$errors[115]['resultcode']=115;$errors[115]['resultmessage']='Не удалось убрать сессию у сотрудника!';
$errors[116]['resultcode']=116;$errors[116]['resultmessage']='Параметр interface не получен!';
$errors[117]['resultcode']=117;$errors[117]['resultmessage']='Сотрудника не сущетвует!';
$errors[118]['resultcode']=118;$errors[118]['resultmessage']='Ошибка выполнения запроса при обновлении последнего действия!';
$errors[119]['resultcode']=119;$errors[119]['resultmessage']='Клиент  с таким штрих кодом не существует!';
$errors[120]['resultcode']=120;$errors[120]['resultmessage']='Не хватает балов!';
$errors[121]['resultcode']=121;$errors[121]['resultmessage']='Ошибка выполнения запроса при проверке надобности обновления меню';
$errors[122]['resultcode']=122;$errors[122]['resultmessage']='Ошибка выполнения запроса при выборе помещения!';
$errors[123]['resultcode']=123;$errors[123]['resultmessage']='Не получен параметр roomid помещения!';
$errors[124]['resultcode']=124;$errors[124]['resultmessage']='Ошибка выполнения запроса при загрузке табличной части regCheck!';
$errors[125]['resultcode']=125;$errors[125]['resultmessage']='Не получен параметр ShtrihRegCheck помещения!!';
$errors[126]['resultcode']=126;$errors[126]['resultmessage']='Ошибка выполнения запроса при регистрации чека!';
$errors[127]['resultcode']=127;$errors[127]['resultmessage']='Ошибка выполнения запроса при проверке регистрации чека!';
$errors[128]['resultcode']=128;$errors[128]['resultmessage']='Чек уже зарегистрирован!';
$errors[129]['resultcode']=129;$errors[129]['resultmessage']='Не получен параметр пароль для выбора клиентов!';
$errors[130]['resultcode']=130;$errors[130]['resultmessage']='Параметр parentid не получен!';
$errors[131]['resultcode']=131;$errors[131]['resultmessage']='Не верный пароль для выбора клиентов!';
$errors[132]['resultcode']=132;$errors[132]['resultmessage']='Параметр itemid не получен!';
$errors[133]['resultcode']=133;$errors[133]['resultmessage']='Ошибка выполнения запроса при добавлении товаров в стоп-лист!';
$errors[134]['resultcode']=134;$errors[134]['resultmessage']='Параметр menuid не получен!';
$errors[135]['resultcode']=135;$errors[135]['resultmessage']='Товар уже в стоп-листе!';
$errors[136]['resultcode']=136;$errors[136]['resultmessage']='Параметр row не получен!';
$errors[137]['resultcode']=137;$errors[137]['resultmessage']='Закрытый или распечатанный счет не может быть разбит!';
$errors[138]['resultcode']=138;$errors[138]['resultmessage']='Неверный пароль на выбор клиентов!';
$errors[139]['resultcode']=139;$errors[139]['resultmessage']='Параметр orderNum не получен!';
$errors[140]['resultcode']=140;$errors[140]['resultmessage']='Параметр date не получен!';
$errors[141]['resultcode']=141;$errors[141]['resultmessage']='Не верный пароль на возврат!';
$errors[142]['resultcode']=142;$errors[142]['resultmessage']='Не верный пароль на стоп лист!';
$errors[143]['resultcode']=143;$errors[143]['resultmessage']='Не верный пароль на акт реализации!';
$errors[144]['resultcode']=144;$errors[144]['resultmessage']='Не верный пароль на отчет по счетам!';
$errors[145]['resultcode']=145;$errors[145]['resultmessage']='Не верный пароль на итоговый отчет!';
$errors[146]['resultcode']=146;$errors[146]['resultmessage']='Не верный пароль на заказы и отказы!';
$errors[147]['resultcode']=147;$errors[147]['resultmessage']='Не верный пароль на отчет по отказам!';
$errors[148]['resultcode']=148;$errors[148]['resultmessage']='Не верный пароль на акт Х отчет!';
$errors[149]['resultcode']=149;$errors[149]['resultmessage']='Не верный пароль на добавление клиента!';
$errors[150]['resultcode']=150;$errors[150]['resultmessage']='Параметр clientData не получен!';
$errors[151]['resultcode']=151;$errors[151]['resultmessage']='Ошибка выполнения запроса при добавлении клиента!';
$errors[152]['resultcode']=152;$errors[152]['resultmessage']='Клиент с таким номером карты уже существует!';
$errors[153]['resultcode']=153;$errors[153]['resultmessage']='Вы не ввели ФИО клиента!';
$errors[154]['resultcode']=154;$errors[154]['resultmessage']='Ошибка входа в модуль Учета Рабочего Времени!';
$errors[155]['resultcode']=155;$errors[155]['resultmessage']='Ошибка выполнения запроса при выборе заказа при возврате!';
$errors[156]['resultcode']=156;$errors[156]['resultmessage']='Ошибка при загрузке конфигурации программы!';
$errors[157]['resultcode']=157;$errors[157]['resultmessage']='Параметр comboItemId не получен!';
$errors[158]['resultcode']=158;$errors[158]['resultmessage']='Ошибка выполнения запроса при выборе комбо группы!';
$errors[159]['resultcode']=159;$errors[159]['resultmessage']='Параметр row не получен!';
$errors[160]['resultcode']=160;$errors[160]['resultmessage']='В данной комбо-группе есть элементы!';
$errors[161]['resultcode']=161;$errors[161]['resultmessage']='Не указано имя группы или параметр name не получен!';
$errors[162]['resultcode']=162;$errors[162]['resultmessage']='Не указана цена группы или цену ввели неправильно или параметр price не получен!';
$errors[163]['resultcode']=163;$errors[163]['resultmessage']='Не указано минимальное количество или минимальное количество введено неправильно или параметр mincount не получен!';
$errors[164]['resultcode']=164;$errors[164]['resultmessage']='Не указано максимальное количество или максимальное количество введено неправильно или параметр maxcount не получен!!';
$errors[165]['resultcode']=165;$errors[165]['resultmessage']='Параметр itemid не получен';
$errors[166]['resultcode']=166;$errors[166]['resultmessage']='Минимальное количество не может быть больше максимального количества!';
$errors[167]['resultcode']=167;$errors[167]['resultmessage']='Не верный пароль на разбиение счета!';
$errors[168]['resultcode']=168;$errors[168]['resultmessage']='Ошибка выполнения запроса при обновлении свойств комбо группы!';
$errors[169]['resultcode']=169;$errors[169]['resultmessage']='Ошибка выполнения запроса при удалении комбо элемента!';
$errors[170]['resultcode']=170;$errors[170]['resultmessage']='Не верный пароль на скидку!';
$errors[171]['resultcode']=171;$errors[171]['resultmessage']='Нельзя продавать товар по нулевым ценам!';
$errors[172]['resultcode']=172;$errors[172]['resultmessage']='Не верный пароль на удаление позиции из заказа!';
$errors[173]['resultcode']=173;$errors[173]['resultmessage']='Данные о записи к мастеру не получены!';
$errors[174]['resultcode']=174;$errors[174]['resultmessage']='Ошибка выполнения запроса при добавлении новой записи в жрунал записей!';
$errors[175]['resultcode']=175;$errors[175]['resultmessage']='Не получен параметр типа операции!';
$errors[176]['resultcode']=176;$errors[176]['resultmessage']='Не получена дата записи!';
$errors[177]['resultcode']=177;$errors[177]['resultmessage']='Не получен id сотрудника к которому производится запись!';
$errors[178]['resultcode']=178;$errors[178]['resultmessage']='Не получено примечание записи!';
$errors[179]['resultcode']=179;$errors[179]['resultmessage']='Не получен id клиента!';
$errors[180]['resultcode']=180;$errors[180]['resultmessage']='Не получено время начала!';
$errors[181]['resultcode']=181;$errors[181]['resultmessage']='Не получено время окончания!';
$errors[182]['resultcode']=182;$errors[182]['resultmessage']='Не получен параметр id записи!';
$errors[183]['resultcode']=183;$errors[183]['resultmessage']='Ошибка выполнения запроса смены сотрудника у счета!';
$errors[184]['resultcode']=184;$errors[184]['resultmessage']='Параметр флаг не получен!';
$errors[185]['resultcode']=185;$errors[185]['resultmessage']='Ошибка завершения транзакции при сохранении счета!';
$errors[186]['resultcode']=186;$errors[186]['resultmessage']='Ошибка старта транзакции при сохранении счета!'; 
$errors[187]['resultcode']=187;$errors[187]['resultmessage']='Ошибка завершения транзакции при возврате позиции счета!';
$errors[188]['resultcode']=188;$errors[188]['resultmessage']='Ошибка старта транзакции при возврате позиции счета!'; 


$errors[500]['resultcode']=500;$errors[500]['resultmessage']='Ошибок нет!';
$errors[501]['resultcode']=501;$errors[501]['resultmessage']='Не получен параметр Location!';
$errors[502]['resultcode']=502;$errors[502]['resultmessage']='Не получен параметр date!';
$errors[503]['resultcode']=503;$errors[503]['resultmessage']='Нет такой команды!';
$errors[504]['resultcode']=504;$errors[504]['resultmessage']='Ошибка выполнения запроса при выборе объектов!';
$errors[505]['resultcode']=505;$errors[505]['resultmessage']='Ошибка выполнения запроса при выборе помещений!';
$errors[506]['resultcode']=506;$errors[506]['resultmessage']='Не получен параметр type!';
$errors[507]['resultcode']=507;$errors[507]['resultmessage']='Не получен параметр dtBegin!';
$errors[508]['resultcode']=508;$errors[508]['resultmessage']='Не получен параметр employeeid!';
$errors[509]['resultcode']=509;$errors[509]['resultmessage']='Не получен параметр clientid!';
$errors[510]['resultcode']=510;$errors[510]['resultmessage']='Не получен параметр objId!';
$errors[511]['resultcode']=511;$errors[511]['resultmessage']='Не получен параметр timeBegin!';
$errors[512]['resultcode']=512;$errors[512]['resultmessage']='Не получен параметр timeEnd!';
$errors[513]['resultcode']=513;$errors[513]['resultmessage']='Не получен параметр note';
$errors[514]['resultcode']=514;$errors[514]['resultmessage']='Время начала или время окончания выходят за рабочий диапазон!';
$errors[515]['resultcode']=515;$errors[515]['resultmessage']='Дата записи меньше текущей даты!';
$errors[516]['resultcode']=516;$errors[516]['resultmessage']='Время начала не может быть больше времени окончания!';
$errors[517]['resultcode']=517;$errors[517]['resultmessage']='Время записи меньше рабочего времени!';
$errors[518]['resultcode']=518;$errors[518]['resultmessage']='Не получен парамтр Jid!';
$errors[519]['resultcode']=519;$errors[519]['resultmessage']='Ошибка вполнения запроса при создании записи в финтнес журнале!';
$errors[520]['resultcode']=520;$errors[520]['resultmessage']='Ошибка вполнения запроса при получении данных о записи!';
$errors[521]['resultcode']=521;$errors[521]['resultmessage']='Не получен параметр parentid!';
$errors[522]['resultcode']=522;$errors[522]['resultmessage']='Не получен параметр orderId!';
$errors[523]['resultcode']=523;$errors[523]['resultmessage']='Не получен параметр orderT!';
$errors[524]['resultcode']=524;$errors[524]['resultmessage']='Не получен параметр id!';

function errcode($index){
   global $errors;
   return $errors[$index]['resultcode'];    
}
function errmsg($index){
    global $errors;
    return $errors[$index]['resultmessage'];    
}
?>
